INSERT INTO PROYECTOS 
(DESCRIPCION)
VALUES ('MIGRACION SQL');

INSERT INTO PROYECTOS 
(DESCRIPCION)
VALUES ('MIGRACION GIRAFE 1.0 A 1.5');

INSERT INTO PROYECTOS 
(DESCRIPCION)
SELECT 'RRHH 5.5';

-- Proyecto WebMail 2.1 de la guía 6.1.1 Manejo de proyectos
INSERT INTO PROYECTOS 
(DESCRIPCION)
SELECT 'Webmail 2.1';

INSERT INTO IMPUESTOS
(DESCRIPCION, VALOR)
VALUES ('A', 3);

INSERT INTO IMPUESTOS
(DESCRIPCION, VALOR)
VALUES ('B', 5);

SELECT ID 
  INTO @Webmail
  FROM PROYECTOS 
 WHERE DESCRIPCION = 'Webmail 2.1'
 LIMIT 1;

INSERT INTO TAREAS
(COMPLEJIDAD, TIEMPO, DESCRIPCION, PROYECTO_ID)
VALUES
('I', 10, 'Relevamiento', @Webmail);

INSERT INTO TAREAS
(COMPLEJIDAD, TIEMPO, DESCRIPCION, PROYECTO_ID)
VALUES
('E', 30, 'Desarrollo', @Webmail);

INSERT INTO TAREAS
(COMPLEJIDAD, TIEMPO, DESCRIPCION, PROYECTO_ID)
VALUES
('A', 2, 'Implementación', @Webmail);

SELECT ID 
  INTO @Desarrollo
  FROM TAREAS 
 WHERE DESCRIPCION = 'Desarrollo'
 LIMIT 1;

INSERT INTO TAREAS
(COMPLEJIDAD, TIEMPO, DESCRIPCION, PROYECTO_ID, TAREAPADRE_ID)
VALUES
('E', 5, 'Iteración 1', @Webmail, @Desarrollo);

INSERT INTO TAREAS
(COMPLEJIDAD, TIEMPO, DESCRIPCION, PROYECTO_ID, TAREAPADRE_ID)
VALUES
('I', 2, 'Iteración 2', @Webmail, @Desarrollo);

INSERT INTO TAREAS
(COMPLEJIDAD, TIEMPO, DESCRIPCION, PROYECTO_ID, TAREAPADRE_ID)
VALUES
('A', 20, 'Iteración 3', @Webmail, @Desarrollo);

SELECT ID 
  INTO @Implementacion
  FROM TAREAS 
 WHERE DESCRIPCION = 'Implementación'
 LIMIT 1;

INSERT INTO TAREAS
(COMPLEJIDAD, TIEMPO, DESCRIPCION, PROYECTO_ID, TAREAPADRE_ID)
VALUES
('I', 2, 'Implementación Sucursal Central', @Webmail, @Implementacion);

INSERT INTO TAREAS
(COMPLEJIDAD, TIEMPO, DESCRIPCION, PROYECTO_ID, TAREAPADRE_ID)
VALUES
('E', 3, 'Implementación Sucursal Liniers', @Webmail, @Implementacion);

-- Proyecto del enunciado
INSERT INTO PROYECTOS 
(DESCRIPCION)
SELECT 'Proyecto A';

SELECT ID 
  INTO @ProyectoA
  FROM PROYECTOS 
 WHERE DESCRIPCION = 'Proyecto A'
 LIMIT 1;
 
INSERT INTO TAREAS
(COMPLEJIDAD, TIEMPO, DESCRIPCION, PROYECTO_ID)
VALUES
('A', 30, 'Tarea 1', @ProyectoA);

INSERT INTO TAREAS
(COMPLEJIDAD, TIEMPO, DESCRIPCION, PROYECTO_ID)
VALUES
('E', 15, 'Tarea 2', @ProyectoA);

INSERT INTO TAREAS
(COMPLEJIDAD, TIEMPO, DESCRIPCION, PROYECTO_ID)
VALUES
('I', 25, 'Tarea 3', @ProyectoA);

SELECT ID 
  INTO @Tarea2
  FROM TAREAS 
 WHERE DESCRIPCION = 'Tarea 2'
 LIMIT 1;

INSERT INTO TAREAS
(COMPLEJIDAD, TIEMPO, DESCRIPCION, PROYECTO_ID, TAREAPADRE_ID)
VALUES
('I', 8, 'subtarea 1', @ProyectoA, @Tarea2);

INSERT INTO TAREAS
(COMPLEJIDAD, TIEMPO, DESCRIPCION, PROYECTO_ID, TAREAPADRE_ID)
VALUES
('E', 5, 'subtarea 2', @ProyectoA, @Tarea2);

