--  1 Saber las tareas que tienen más de una subtarea.
/*

DROP VIEW TAREAS_CON_MAS_DE_UNA_SUBTAREA;

-- Esta opción muestra la descripción de las tareas padres

CREATE VIEW TAREAS_CON_MAS_DE_UNA_SUBTAREA AS
SELECT TAREA_PADRE.DESCRIPCION, COUNT(*) AS CANTIDAD_SUBTAREAS
  FROM TAREAS SUBTAREAS,
       TAREAS TAREA_PADRE
 WHERE SUBTAREAS.TAREAPADRE_ID IS NOT NULL
   AND SUBTAREAS.TAREAPADRE_ID = TAREA_PADRE.ID
 GROUP 
    BY SUBTAREAS.TAREAPADRE_ID
HAVING COUNT(*) > 1 ;
*/

DROP VIEW IF EXISTS TAREAS_CON_MAS_DE_UNA_SUBTAREA;

CREATE VIEW TAREAS_CON_MAS_DE_UNA_SUBTAREA AS
SELECT TAREAPADRE_ID, COUNT(*) AS CANTIDAD_SUBTAREAS
  FROM TAREAS
 WHERE TAREAPADRE_ID IS NOT NULL
 GROUP 
    BY TAREAPADRE_ID
HAVING COUNT(*) > 1 ;

DROP VIEW IF EXISTS TAREAS_CON_OVERHEAD;

CREATE VIEW TAREAS_CON_OVERHEAD AS
SELECT TAREAPADRE_ID, COUNT(*) AS CANTIDAD_SUBTAREAS
  FROM TAREAS
 WHERE TAREAPADRE_ID IS NOT NULL
 GROUP 
    BY TAREAPADRE_ID
HAVING COUNT(*) > 3 ;





