-- 2 Saber si un proyecto tiene alguna tarea que contenga el string "subtarea" 
DROP VIEW IF EXISTS TAREAS_QUE_CONTENGAN_SUBTAREA;

CREATE VIEW TAREAS_QUE_CONTENGAN_SUBTAREA AS
SELECT PROYECTOS.DESCRIPCION AS DESCRIPCION_PROYECTO, 
       TAREAS.DESCRIPCION AS DESCRIPCION_TAREA
  FROM TAREAS,
       PROYECTOS 
 WHERE TAREAS.PROYECTO_ID = PROYECTOS.ID
   AND UPPER(TAREAS.DESCRIPCION) LIKE '%SUBTAREA%';
   
SELECT *
  FROM TAREAS_QUE_CONTENGAN_SUBTAREA;


